### PR TITLE
Week 2 index page with HTML CSS and JS plust images update

### PR DESCRIPTION
**Pull request by twkclaire**
Please review 2nd week assignment 

Update week 1 nextpage strategy 
Update index page content, css and js 

name:高廷薇
website: http://18.199.186.172:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Your code load the same page multiple times if we scroll down and up quickly.
- Your code may skip some pages. Next page number should depend on nextPage field of server response, not just add 1.
- If we search 北, there should have 2 pages data.
未命名-2

**Comment by twkclaire** [comment]
Please check the updated version again ^_^

Your code load the same page multiple times if we scroll down and up quickly. -> **implement debounce**
Your code may skip some pages. Next page number should depend on nextPage field of server response, not just add 1. -> **Good catch. set page =nextPage in and of function**
If we search 北, there should have 2 pages data. **fixed**

@cwpeng

**Review by cwpeng — CHANGES_REQUESTED** [review]
I scroll to the bottom, up and bottom again, wait a very long time (maybe 15 seconds), finally get the next page. It's unacceptable.

**Comment by twkclaire** [comment]
The problem was how I set up the intersection observer. The previous setting resulted in an endless loop of footer observation without properly triggering the fetch function. 

Please check again!
@cwpeng

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code load the same page multiple times if we scroll down and up quickly.
未命名-2

**Comment by twkclaire** [comment]
@cwpeng 
please check the new update! Thanks!

**Comment by cwpeng** [comment]
Cannot load next page data.

**Comment by twkclaire** [comment]
@cwpeng what about now?

**Review by cwpeng — CHANGES_REQUESTED** [review]
https://github.com/twkclaire/taipei-day-trip/assets/6104683/9b13e3dc-c3c9-46e7-aa88-cd72a8465391

**Comment by twkclaire** [comment]
@cwpeng 
Wasn't able to reproduce error with Chrome. 
Tested on Firefox and was able to reproduced the same error.
Suspected the problem being footer is not fully visible to some browser.
Changed observing threshold and tested on browser and don't see the said error again. Please check again!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
